package defpackage;

import android.view.ViewGroup;
import com.jcraft.jsch.SftpATTRS;
import java.util.Arrays;
import java.util.HashMap;

/* JADX INFO: compiled from: r8-map-id-1bff7581625143effd57ac0798e0b9b336d7bf32101928a795c6093adf9a91d0 */
/* JADX INFO: loaded from: classes.dex */
public final class it1 {
    public int a;
    public final lt1 b;
    public final kt1 c;
    public final jt1 d;
    public final mt1 e;
    public HashMap f;

    public it1() {
        lt1 lt1Var = new lt1();
        lt1Var.a = 0;
        lt1Var.b = 0;
        lt1Var.c = 1.0f;
        lt1Var.d = Float.NaN;
        this.b = lt1Var;
        kt1 kt1Var = new kt1();
        kt1Var.a = -1;
        kt1Var.b = 0;
        kt1Var.c = -1;
        kt1Var.d = Float.NaN;
        kt1Var.e = Float.NaN;
        kt1Var.f = Float.NaN;
        kt1Var.g = -1;
        kt1Var.h = null;
        kt1Var.i = -1;
        this.c = kt1Var;
        jt1 jt1Var = new jt1();
        jt1Var.a = false;
        jt1Var.d = -1;
        jt1Var.e = -1;
        jt1Var.f = -1.0f;
        jt1Var.g = true;
        jt1Var.h = -1;
        jt1Var.i = -1;
        jt1Var.j = -1;
        jt1Var.k = -1;
        jt1Var.l = -1;
        jt1Var.m = -1;
        jt1Var.n = -1;
        jt1Var.o = -1;
        jt1Var.p = -1;
        jt1Var.q = -1;
        jt1Var.r = -1;
        jt1Var.s = -1;
        jt1Var.t = -1;
        jt1Var.u = -1;
        jt1Var.v = -1;
        jt1Var.w = 0.5f;
        jt1Var.x = 0.5f;
        jt1Var.y = null;
        jt1Var.z = -1;
        jt1Var.A = 0;
        jt1Var.B = 0.0f;
        jt1Var.C = -1;
        jt1Var.D = -1;
        jt1Var.E = -1;
        jt1Var.F = 0;
        jt1Var.G = 0;
        jt1Var.H = 0;
        jt1Var.I = 0;
        jt1Var.J = 0;
        jt1Var.K = 0;
        jt1Var.L = 0;
        jt1Var.M = SftpATTRS.SSH_FILEXFER_ATTR_EXTENDED;
        jt1Var.N = SftpATTRS.SSH_FILEXFER_ATTR_EXTENDED;
        jt1Var.O = SftpATTRS.SSH_FILEXFER_ATTR_EXTENDED;
        jt1Var.P = SftpATTRS.SSH_FILEXFER_ATTR_EXTENDED;
        jt1Var.Q = SftpATTRS.SSH_FILEXFER_ATTR_EXTENDED;
        jt1Var.R = SftpATTRS.SSH_FILEXFER_ATTR_EXTENDED;
        jt1Var.S = SftpATTRS.SSH_FILEXFER_ATTR_EXTENDED;
        jt1Var.T = -1.0f;
        jt1Var.U = -1.0f;
        jt1Var.V = 0;
        jt1Var.W = 0;
        jt1Var.X = 0;
        jt1Var.Y = 0;
        jt1Var.Z = 0;
        jt1Var.a0 = 0;
        jt1Var.b0 = 0;
        jt1Var.c0 = 0;
        jt1Var.d0 = 1.0f;
        jt1Var.e0 = 1.0f;
        jt1Var.f0 = -1;
        jt1Var.g0 = 0;
        jt1Var.h0 = -1;
        jt1Var.l0 = false;
        jt1Var.m0 = false;
        jt1Var.n0 = true;
        jt1Var.o0 = 0;
        this.d = jt1Var;
        mt1 mt1Var = new mt1();
        mt1Var.a = 0.0f;
        mt1Var.b = 0.0f;
        mt1Var.c = 0.0f;
        mt1Var.d = 1.0f;
        mt1Var.e = 1.0f;
        mt1Var.f = Float.NaN;
        mt1Var.g = Float.NaN;
        mt1Var.h = -1;
        mt1Var.i = 0.0f;
        mt1Var.j = 0.0f;
        mt1Var.k = 0.0f;
        mt1Var.l = false;
        mt1Var.m = 0.0f;
        this.e = mt1Var;
        this.f = new HashMap();
    }

    public final void a(dt1 dt1Var) {
        jt1 jt1Var = this.d;
        dt1Var.e = jt1Var.h;
        dt1Var.f = jt1Var.i;
        dt1Var.g = jt1Var.j;
        dt1Var.h = jt1Var.k;
        dt1Var.i = jt1Var.l;
        dt1Var.j = jt1Var.m;
        dt1Var.k = jt1Var.n;
        dt1Var.l = jt1Var.o;
        dt1Var.m = jt1Var.p;
        dt1Var.n = jt1Var.q;
        dt1Var.o = jt1Var.r;
        dt1Var.s = jt1Var.s;
        dt1Var.t = jt1Var.t;
        dt1Var.u = jt1Var.u;
        dt1Var.v = jt1Var.v;
        ((ViewGroup.MarginLayoutParams) dt1Var).leftMargin = jt1Var.F;
        ((ViewGroup.MarginLayoutParams) dt1Var).rightMargin = jt1Var.G;
        ((ViewGroup.MarginLayoutParams) dt1Var).topMargin = jt1Var.H;
        ((ViewGroup.MarginLayoutParams) dt1Var).bottomMargin = jt1Var.I;
        dt1Var.A = jt1Var.R;
        dt1Var.B = jt1Var.Q;
        dt1Var.x = jt1Var.N;
        dt1Var.z = jt1Var.P;
        dt1Var.E = jt1Var.w;
        dt1Var.F = jt1Var.x;
        dt1Var.p = jt1Var.z;
        dt1Var.q = jt1Var.A;
        dt1Var.r = jt1Var.B;
        dt1Var.G = jt1Var.y;
        dt1Var.T = jt1Var.C;
        dt1Var.U = jt1Var.D;
        dt1Var.I = jt1Var.T;
        dt1Var.H = jt1Var.U;
        dt1Var.K = jt1Var.W;
        dt1Var.J = jt1Var.V;
        dt1Var.W = jt1Var.l0;
        dt1Var.X = jt1Var.m0;
        dt1Var.L = jt1Var.X;
        dt1Var.M = jt1Var.Y;
        dt1Var.P = jt1Var.Z;
        dt1Var.Q = jt1Var.a0;
        dt1Var.N = jt1Var.b0;
        dt1Var.O = jt1Var.c0;
        dt1Var.R = jt1Var.d0;
        dt1Var.S = jt1Var.e0;
        dt1Var.V = jt1Var.E;
        dt1Var.c = jt1Var.f;
        dt1Var.a = jt1Var.d;
        dt1Var.b = jt1Var.e;
        ((ViewGroup.MarginLayoutParams) dt1Var).width = jt1Var.b;
        ((ViewGroup.MarginLayoutParams) dt1Var).height = jt1Var.c;
        String str = jt1Var.k0;
        if (str != null) {
            dt1Var.Y = str;
        }
        dt1Var.Z = jt1Var.o0;
        dt1Var.setMarginStart(jt1Var.K);
        dt1Var.setMarginEnd(jt1Var.J);
        dt1Var.a();
    }

    public final Object clone() {
        it1 it1Var = new it1();
        jt1 jt1Var = it1Var.d;
        jt1Var.getClass();
        jt1 jt1Var2 = this.d;
        jt1Var.a = jt1Var2.a;
        jt1Var.b = jt1Var2.b;
        jt1Var.c = jt1Var2.c;
        jt1Var.d = jt1Var2.d;
        jt1Var.e = jt1Var2.e;
        jt1Var.f = jt1Var2.f;
        jt1Var.g = jt1Var2.g;
        jt1Var.h = jt1Var2.h;
        jt1Var.i = jt1Var2.i;
        jt1Var.j = jt1Var2.j;
        jt1Var.k = jt1Var2.k;
        jt1Var.l = jt1Var2.l;
        jt1Var.m = jt1Var2.m;
        jt1Var.n = jt1Var2.n;
        jt1Var.o = jt1Var2.o;
        jt1Var.p = jt1Var2.p;
        jt1Var.q = jt1Var2.q;
        jt1Var.r = jt1Var2.r;
        jt1Var.s = jt1Var2.s;
        jt1Var.t = jt1Var2.t;
        jt1Var.u = jt1Var2.u;
        jt1Var.v = jt1Var2.v;
        jt1Var.w = jt1Var2.w;
        jt1Var.x = jt1Var2.x;
        jt1Var.y = jt1Var2.y;
        jt1Var.z = jt1Var2.z;
        jt1Var.A = jt1Var2.A;
        jt1Var.B = jt1Var2.B;
        jt1Var.C = jt1Var2.C;
        jt1Var.D = jt1Var2.D;
        jt1Var.E = jt1Var2.E;
        jt1Var.F = jt1Var2.F;
        jt1Var.G = jt1Var2.G;
        jt1Var.H = jt1Var2.H;
        jt1Var.I = jt1Var2.I;
        jt1Var.J = jt1Var2.J;
        jt1Var.K = jt1Var2.K;
        jt1Var.L = jt1Var2.L;
        jt1Var.M = jt1Var2.M;
        jt1Var.N = jt1Var2.N;
        jt1Var.O = jt1Var2.O;
        jt1Var.P = jt1Var2.P;
        jt1Var.Q = jt1Var2.Q;
        jt1Var.R = jt1Var2.R;
        jt1Var.S = jt1Var2.S;
        jt1Var.T = jt1Var2.T;
        jt1Var.U = jt1Var2.U;
        jt1Var.V = jt1Var2.V;
        jt1Var.W = jt1Var2.W;
        jt1Var.X = jt1Var2.X;
        jt1Var.Y = jt1Var2.Y;
        jt1Var.Z = jt1Var2.Z;
        jt1Var.a0 = jt1Var2.a0;
        jt1Var.b0 = jt1Var2.b0;
        jt1Var.c0 = jt1Var2.c0;
        jt1Var.d0 = jt1Var2.d0;
        jt1Var.e0 = jt1Var2.e0;
        jt1Var.f0 = jt1Var2.f0;
        jt1Var.g0 = jt1Var2.g0;
        jt1Var.h0 = jt1Var2.h0;
        jt1Var.k0 = jt1Var2.k0;
        int[] iArr = jt1Var2.i0;
        if (iArr == null || jt1Var2.j0 != null) {
            jt1Var.i0 = null;
        } else {
            jt1Var.i0 = Arrays.copyOf(iArr, iArr.length);
        }
        jt1Var.j0 = jt1Var2.j0;
        jt1Var.l0 = jt1Var2.l0;
        jt1Var.m0 = jt1Var2.m0;
        jt1Var.n0 = jt1Var2.n0;
        jt1Var.o0 = jt1Var2.o0;
        kt1 kt1Var = it1Var.c;
        kt1Var.getClass();
        kt1 kt1Var2 = this.c;
        kt1Var2.getClass();
        kt1Var.a = kt1Var2.a;
        kt1Var.c = kt1Var2.c;
        kt1Var.e = kt1Var2.e;
        kt1Var.d = kt1Var2.d;
        lt1 lt1Var = this.b;
        int i = lt1Var.a;
        lt1 lt1Var2 = it1Var.b;
        lt1Var2.a = i;
        lt1Var2.c = lt1Var.c;
        lt1Var2.d = lt1Var.d;
        lt1Var2.b = lt1Var.b;
        mt1 mt1Var = it1Var.e;
        mt1Var.getClass();
        mt1 mt1Var2 = this.e;
        mt1Var2.getClass();
        mt1Var.a = mt1Var2.a;
        mt1Var.b = mt1Var2.b;
        mt1Var.c = mt1Var2.c;
        mt1Var.d = mt1Var2.d;
        mt1Var.e = mt1Var2.e;
        mt1Var.f = mt1Var2.f;
        mt1Var.g = mt1Var2.g;
        mt1Var.h = mt1Var2.h;
        mt1Var.i = mt1Var2.i;
        mt1Var.j = mt1Var2.j;
        mt1Var.k = mt1Var2.k;
        mt1Var.l = mt1Var2.l;
        mt1Var.m = mt1Var2.m;
        it1Var.a = this.a;
        return it1Var;
    }
}
