package defpackage;

import java.io.IOException;
import java.util.HashMap;
import org.bouncycastle.asn1.x509.SubjectPublicKeyInfo;

/* JADX INFO: loaded from: classes.dex */
public abstract class mb6 {
    public static final HashMap a;

    static {
        HashMap map = new HashMap();
        a = map;
        map.put(bw5.a, new db6(1));
        map.put(bw5.b, new ib6());
        map.put(bw5.c, new gb6(1));
        map.put(bw5.d, new hb6(1));
        map.put(pg4.a, new gb6(1));
        map.put(pg4.b, new hb6(1));
        map.put(tv5.a, new eb6(0));
        fz5.t(map, vg0.d);
        fz5.t(map, vg0.e);
        fz5.t(map, vg0.f);
        fz5.t(map, vg0.g);
        fz5.t(map, vg0.h);
        fz5.t(map, vg0.i);
        fz5.t(map, vg0.j);
        fz5.t(map, vg0.k);
        fz5.t(map, vg0.l);
        fz5.t(map, vg0.m);
        fz5.t(map, vg0.n);
        fz5.t(map, vg0.o);
        fz5.t(map, vg0.p);
        fz5.t(map, vg0.q);
        fz5.t(map, vg0.r);
        fz5.t(map, vg0.s);
        fz5.t(map, vg0.t);
        fz5.t(map, vg0.u);
        fz5.t(map, vg0.v);
        fz5.t(map, vg0.A);
        fz5.t(map, vg0.B);
        fz5.t(map, vg0.G);
        fz5.t(map, vg0.H);
        fz5.t(map, vg0.M);
        fz5.t(map, vg0.N);
        fz5.t(map, vg0.Q);
        fz5.t(map, vg0.P);
        fz5.t(map, vg0.W);
        fz5.t(map, vg0.V);
        fz5.t(map, vg0.S);
        fz5.t(map, vg0.R);
        fz5.t(map, vg0.Y);
        fz5.t(map, vg0.X);
        fz5.t(map, vg0.U);
        fz5.t(map, vg0.T);
        fz5.t(map, vg0.a0);
        map.put(vg0.Z, new eb6(1));
        fz5.t(map, new f1("1.3.9999.6.4.10"));
        map.put(vg0.I0, new za6(0));
        map.put(vg0.J0, new za6(0));
        map.put(vg0.K0, new za6(0));
        map.put(vg0.L0, new za6(0));
        map.put(vg0.M0, new za6(0));
        map.put(vg0.N0, new za6(0));
        map.put(vg0.O0, new za6(0));
        map.put(vg0.P0, new za6(0));
        map.put(vg0.Q0, new za6(0));
        map.put(vg0.R0, new za6(0));
        map.put(vg0.T0, new cb6(0));
        map.put(vg0.U0, new cb6(0));
        map.put(vg0.V0, new cb6(0));
        map.put(vg0.W0, new cb6(0));
        map.put(vg0.X0, new cb6(0));
        map.put(vg0.Y0, new cb6(0));
        map.put(vg0.a1, new ab6(1));
        map.put(vg0.b1, new ab6(1));
        map.put(vg0.c1, new ab6(1));
        map.put(vg0.d1, new ab6(1));
        map.put(vg0.e1, new ab6(1));
        map.put(vg0.f1, new ab6(1));
        map.put(vg0.g1, new ab6(1));
        map.put(vg0.h1, new ab6(1));
        map.put(vg0.i1, new ab6(1));
        map.put(vg0.j1, new ab6(1));
        map.put(vg0.k1, new ab6(1));
        map.put(vg0.l1, new ab6(1));
        map.put(vg0.m1, new ab6(1));
        map.put(vg0.n1, new ab6(1));
        map.put(vg0.o1, new ab6(1));
        map.put(vg0.p1, new ab6(1));
        map.put(vg0.q1, new ab6(1));
        map.put(vg0.r1, new ab6(1));
        map.put(vg0.d0, new ya6(1));
        map.put(vg0.e0, new ya6(1));
        map.put(vg0.f0, new ya6(1));
        map.put(vg0.g0, new ya6(1));
        map.put(vg0.h0, new ya6(1));
        map.put(vg0.i0, new ya6(1));
        map.put(vg0.j0, new ya6(1));
        map.put(vg0.k0, new ya6(1));
        map.put(vg0.l0, new ya6(1));
        map.put(vg0.m0, new ya6(1));
        map.put(vg0.n0, new ya6(1));
        map.put(vg0.o0, new ya6(1));
        map.put(vg0.t1, new kb6());
        map.put(vg0.u1, new kb6());
        map.put(vg0.v1, new kb6());
        map.put(vg0.x1, new kb6());
        map.put(vg0.w1, new kb6());
        map.put(vg0.y1, new kb6());
        map.put(vg0.r0, new bb6(0));
        map.put(vg0.s0, new bb6(0));
        map.put(vg0.p0, new bb6(0));
        map.put(vg0.q0, new bb6(0));
        map.put(pj5.L, new gb6(0));
        map.put(pj5.M, new gb6(0));
        map.put(pj5.N, new gb6(0));
        map.put(vg0.z1, new gb6(0));
        map.put(vg0.A1, new gb6(0));
        map.put(vg0.B1, new gb6(0));
        map.put(vg0.D1, new jb6());
        map.put(vg0.E1, new jb6());
        map.put(vg0.F1, new jb6());
        map.put(vg0.G1, new jb6());
        map.put(vg0.H1, new jb6());
        map.put(vg0.I1, new jb6());
        map.put(vg0.K1, new cb6(1));
        map.put(vg0.L1, new cb6(1));
        map.put(vg0.M1, new cb6(1));
        map.put(vg0.N1, new cb6(1));
        map.put(vg0.O1, new cb6(1));
        map.put(vg0.P1, new cb6(1));
        map.put(pj5.h, new fb6(0));
        map.put(pj5.i, new fb6(0));
        map.put(pj5.j, new fb6(0));
        map.put(pj5.k, new fb6(0));
        map.put(pj5.l, new fb6(0));
        map.put(pj5.m, new fb6(0));
        map.put(vg0.t0, new ab6(0));
        map.put(vg0.u0, new ab6(0));
        map.put(vg0.v0, new ab6(0));
        map.put(vg0.w0, new ab6(0));
        map.put(vg0.x0, new ab6(0));
        map.put(vg0.y0, new ab6(0));
        map.put(vg0.R1, new ya6(0));
        map.put(vg0.S1, new ya6(0));
        map.put(vg0.T1, new ya6(0));
        map.put(vg0.V1, new db6(0));
        map.put(vg0.W1, new db6(0));
        map.put(vg0.X1, new db6(0));
        map.put(vg0.A0, new za6(1));
        map.put(vg0.B0, new za6(1));
        map.put(vg0.C0, new za6(1));
        map.put(vg0.D0, new za6(1));
        map.put(vg0.E0, new za6(1));
        map.put(vg0.F0, new za6(1));
        fz5.s(map, pj5.n);
        fz5.s(map, pj5.o);
        fz5.s(map, pj5.p);
        fz5.s(map, pj5.q);
        fz5.s(map, pj5.r);
        fz5.s(map, pj5.s);
        fz5.s(map, pj5.t);
        fz5.s(map, pj5.u);
        fz5.s(map, pj5.v);
        fz5.s(map, pj5.w);
        fz5.s(map, pj5.x);
        fz5.s(map, pj5.y);
        fz5.s(map, pj5.z);
        fz5.s(map, pj5.A);
        fz5.s(map, pj5.B);
        fz5.s(map, pj5.C);
        fz5.s(map, pj5.D);
        fz5.s(map, pj5.E);
        fz5.s(map, pj5.F);
        fz5.s(map, pj5.G);
        fz5.s(map, pj5.H);
        fz5.s(map, pj5.I);
        fz5.s(map, pj5.J);
        fz5.s(map, pj5.K);
        map.put(vg0.Z1, new hb6(0));
        map.put(vg0.a2, new hb6(0));
        map.put(vg0.b2, new hb6(0));
        map.put(vg0.c2, new hb6(0));
        fz5.u(map, vg0.f2);
        fz5.u(map, vg0.e2);
        fz5.u(map, vg0.h2);
        fz5.u(map, vg0.g2);
        fz5.u(map, vg0.j2);
        fz5.u(map, vg0.i2);
        fz5.u(map, vg0.l2);
        fz5.u(map, vg0.k2);
        fz5.u(map, vg0.n2);
        fz5.u(map, vg0.m2);
        fz5.u(map, vg0.p2);
        fz5.u(map, vg0.o2);
        fz5.u(map, vg0.r2);
        fz5.u(map, vg0.q2);
        fz5.u(map, vg0.t2);
        fz5.u(map, vg0.s2);
        fz5.u(map, vg0.v2);
        fz5.u(map, vg0.u2);
        fz5.u(map, vg0.x2);
        fz5.u(map, vg0.w2);
        fz5.u(map, vg0.z2);
        fz5.u(map, vg0.y2);
        fz5.u(map, vg0.B2);
        fz5.u(map, vg0.A2);
        fz5.u(map, vg0.D2);
        fz5.u(map, vg0.C2);
        fz5.u(map, vg0.F2);
        fz5.u(map, vg0.E2);
        fz5.u(map, vg0.H2);
        fz5.u(map, vg0.G2);
        fz5.u(map, vg0.J2);
        fz5.u(map, vg0.I2);
        fz5.u(map, vg0.L2);
        fz5.u(map, vg0.K2);
        fz5.u(map, vg0.N2);
        fz5.u(map, vg0.M2);
        fz5.u(map, vg0.P2);
        fz5.u(map, vg0.O2);
        fz5.u(map, vg0.R2);
        fz5.u(map, vg0.Q2);
        fz5.u(map, vg0.T2);
        fz5.u(map, vg0.S2);
        fz5.u(map, vg0.V2);
        fz5.u(map, vg0.U2);
    }

    public static n60 a(SubjectPublicKeyInfo subjectPublicKeyInfo) throws IOException {
        if (subjectPublicKeyInfo == null) {
            c6.f("keyInfo argument null");
            return null;
        }
        ya yaVar = subjectPublicKeyInfo.a;
        lb6 lb6Var = (lb6) a.get(yaVar.a);
        if (lb6Var != null) {
            return lb6Var.a(subjectPublicKeyInfo);
        }
        c6.k(yaVar.a, "algorithm identifier in public key not recognised: ");
        return null;
    }
}
