package defpackage;

/* JADX INFO: loaded from: classes.dex */
public interface pj5 {
    public static final f1 A = Holder.A;
    public static final f1 B = Holder.B;
    public static final f1 C = Holder.C;
    public static final f1 D = Holder.D;
    public static final f1 E = Holder.E;
    public static final f1 F = Holder.F;
    public static final f1 G = Holder.G;
    public static final f1 H = Holder.H;
    public static final f1 I = Holder.I;
    public static final f1 J = Holder.J;
    public static final f1 K = Holder.K;
    public static final f1 L = Holder.L;
    public static final f1 M = Holder.M;
    public static final f1 N = Holder.N;
    public static final f1 a = Holder.a;
    public static final f1 b = Holder.b;
    public static final f1 c = Holder.c;
    public static final f1 d = Holder.d;
    public static final f1 e = Holder.e;
    public static final f1 f = Holder.f;
    public static final f1 g = Holder.g;
    public static final f1 h = Holder.h;
    public static final f1 i = Holder.i;
    public static final f1 j = Holder.j;
    public static final f1 k = Holder.k;
    public static final f1 l = Holder.l;
    public static final f1 m = Holder.m;
    public static final f1 n = Holder.n;
    public static final f1 o = Holder.o;
    public static final f1 p = Holder.p;
    public static final f1 q = Holder.q;
    public static final f1 r = Holder.r;
    public static final f1 s = Holder.s;
    public static final f1 t = Holder.t;
    public static final f1 u = Holder.u;
    public static final f1 v = Holder.v;
    public static final f1 w = Holder.w;
    public static final f1 x = Holder.x;
    public static final f1 y = Holder.y;
    public static final f1 z = Holder.z;

    final class Holder {
        static final f1 a;
        static final f1 b;
        static final f1 c;
        static final f1 d;
        static final f1 e;
        static final f1 f;
        static final f1 g;
        static final f1 h;
        static final f1 i;
        static final f1 j;
        static final f1 k;
        static final f1 l;
        static final f1 m;
        static final f1 n;
        static final f1 o;
        static final f1 p;
        static final f1 q;
        static final f1 r;
        static final f1 s;
        static final f1 t;
        static final f1 u;
        static final f1 v;
        static final f1 w;
        static final f1 x;
        static final f1 y;
        static final f1 z;
        static final f1 A;
        static final f1 B;
        static final f1 C;
        static final f1 D;
        static final f1 E;
        static final f1 F;
        static final f1 G;
        static final f1 H;
        static final f1 I;
        static final f1 J;
        static final f1 K;
        static final f1 L;
        static final f1 M;
        static final f1 N;

        static {
            f1 f1Var = new f1("2.16.840.1.101.3.4");
            f1 f1VarX = f1Var.x("2");
            a = f1VarX.x("1");
            f1VarX.x("2");
            b = f1VarX.x("3");
            f1VarX.x("4");
            f1VarX.x("5");
            c = f1VarX.x("6");
            f1VarX.x("7");
            d = f1VarX.x("8");
            f1VarX.x("9");
            f1VarX.x("10");
            e = f1VarX.x("11");
            f = f1VarX.x("12");
            dj7.x(f1VarX, "13", "14", "15", "16");
            f1VarX.x("17");
            g = f1VarX.x("18");
            dj7.x(f1VarX, "19", "20", "21", "22");

            f1 f1VarX2 = f1Var.x("1");
            f1VarX2.x("1");
            f1VarX2.x("2");
            f1VarX2.x("3");
            dj7.x(f1VarX2, "4", "5", "6", "7");
            dj7.x(f1VarX2, "8", "9", "21", "22");
            dj7.x(f1VarX2, "23", "24", "25", "26");
            dj7.x(f1VarX2, "27", "28", "29", "41");
            dj7.x(f1VarX2, "42", "43", "44", "45");
            dj7.x(f1VarX2, "46", "47", "48", "49");

            f1 f1VarX3 = f1Var.x("3");
            f1VarX3.x("1");
            f1VarX3.x("2");
            f1VarX3.x("3");
            dj7.x(f1VarX3, "4", "5", "6", "7");
            dj7.x(f1VarX3, "8", "9", "10", "11");
            dj7.x(f1VarX3, "12", "13", "14", "15");
            f1VarX3.x("16");
            h = f1VarX3.x("17");
            i = f1VarX3.x("18");
            j = f1VarX3.x("19");
            k = f1VarX3.x("32");
            l = f1VarX3.x("33");
            m = f1VarX3.x("34");
            n = f1VarX3.x("20");
            o = f1VarX3.x("21");
            p = f1VarX3.x("22");
            q = f1VarX3.x("23");
            r = f1VarX3.x("24");
            s = f1VarX3.x("25");
            t = f1VarX3.x("26");
            u = f1VarX3.x("27");
            v = f1VarX3.x("28");
            w = f1VarX3.x("29");
            x = f1VarX3.x("30");
            y = f1VarX3.x("31");
            z = f1VarX3.x("35");
            A = f1VarX3.x("36");
            B = f1VarX3.x("37");
            C = f1VarX3.x("38");
            D = f1VarX3.x("39");
            E = f1VarX3.x("40");
            F = f1VarX3.x("41");
            G = f1VarX3.x("42");
            H = f1VarX3.x("43");
            I = f1VarX3.x("44");
            J = f1VarX3.x("45");
            K = f1VarX3.x("46");

            f1 f1VarX4 = f1Var.x("4");
            L = f1VarX4.x("1");
            M = f1VarX4.x("2");
            N = f1VarX4.x("3");
        }
    }
}
