package com.bare.cloud.connect;
import android.app.Activity; import android.os.Bundle; import android.text.Editable; import android.text.TextWatcher; import android.widget.TextView; import androidx.annotation.Nullable; import androidx.appcompat.app.AppCompatActivity; import com.bare.R; import com.google.android.material.button.MaterialButton; import com.google.android.material.textfield.TextInputEditText; import com.google.android.material.dialog.MaterialAlertDialogBuilder;
public final class FilenSignInActivity extends AppCompatActivity {
 private TextInputEditText email,password; private MaterialButton connect;
 @Override protected void onCreate(@Nullable Bundle state){ super.onCreate(state); setContentView(R.layout.filen_signin_activity); email=findViewById(R.id.et_filen_email); password=findViewById(R.id.et_filen_password); connect=findViewById(R.id.btn_connect_filen); ((TextView)findViewById(R.id.tv_title)).setText(R.string.filen); connect.setEnabled(false); TextWatcher w=new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int b,int c){} public void onTextChanged(CharSequence s,int a,int b,int c){refreshEnabled();} public void afterTextChanged(Editable e){}}; email.addTextChangedListener(w); password.addTextChangedListener(w); connect.setOnClickListener(v->authenticateBoundary()); refreshEnabled(); }
 private void refreshEnabled(){String e=email.getText()==null?"":email.getText().toString().trim(), p=password.getText()==null?"":password.getText().toString(); connect.setEnabled(!e.isEmpty()&&p.length()>0);}
 private void authenticateBoundary(){new MaterialAlertDialogBuilder(this).setTitle(R.string.filen).setMessage(R.string.p3_cloud_auth_boundary).setNegativeButton(R.string.close,null).show();}
 @Override public boolean onSupportNavigateUp(){setResult(Activity.RESULT_CANCELED);finish();return true;}
}
