package com.bare.messagescalls.backuprestore;
import android.app.Activity; import android.app.role.RoleManager; import android.content.Intent; import android.os.Bundle; import android.view.Menu; import android.view.MenuItem; import android.view.View; import androidx.annotation.Nullable; import androidx.appcompat.app.AppCompatActivity; import androidx.appcompat.widget.Toolbar; import androidx.recyclerview.widget.RecyclerView; import androidx.swiperefreshlayout.widget.SwipeRefreshLayout; import com.bare.R; import com.google.android.material.dialog.MaterialAlertDialogBuilder;
public final class MessagesBackupRestoreActivity extends AppCompatActivity{
 private static final int SMS_ROLE_REQUEST=12458; private EmptyAdapter adapter;
 @Override protected void onCreate(@Nullable Bundle s){super.onCreate(s);setContentView(R.layout.smscalls_backup_restore_activity);Toolbar t=findViewById(R.id.toolbar);t.setTitle(R.string.messages_backup);setSupportActionBar(t);if(getSupportActionBar()!=null)getSupportActionBar().setDisplayHomeAsUpEnabled(true);RecyclerView rv=findViewById(R.id.rv_backups);adapter=new EmptyAdapter();rv.setAdapter(adapter);SwipeRefreshLayout refresh=findViewById(R.id.swipe_refresh);refresh.setOnRefreshListener(()->refresh.setRefreshing(false));findViewById(R.id.btn_backup).setOnClickListener(v->boundary(R.string.messages_backup));findViewById(R.id.btn_restore).setOnClickListener(v->requestSmsRole());}
 private void requestSmsRole(){if(android.os.Build.VERSION.SDK_INT>=29){RoleManager rm=getSystemService(RoleManager.class);if(rm!=null&&rm.isRoleAvailable(RoleManager.ROLE_SMS)&&!rm.isRoleHeld(RoleManager.ROLE_SMS)){startActivityForResult(rm.createRequestRoleIntent(RoleManager.ROLE_SMS),SMS_ROLE_REQUEST);return;}}boundary(R.string.restore_messages);}
 @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==SMS_ROLE_REQUEST&&c==RESULT_OK)boundary(R.string.restore_messages);}
 @Override public boolean onCreateOptionsMenu(Menu m){getMenuInflater().inflate(R.menu.menu_select_all,m);m.findItem(R.id.action_select_all).setChecked(false);return true;}
 @Override public boolean onOptionsItemSelected(MenuItem i){if(i.getItemId()==R.id.action_select_all){i.setChecked(!i.isChecked());adapter.selected=i.isChecked();adapter.notifyDataSetChanged();return true;}return super.onOptionsItemSelected(i);}
 private void boundary(int title){new MaterialAlertDialogBuilder(this).setTitle(title).setMessage(R.string.p3_activity_boundary).setPositiveButton(R.string.close,null).show();}
 @Override public boolean onSupportNavigateUp(){setResult(Activity.RESULT_CANCELED);finish();return true;}
 private static final class EmptyAdapter extends RecyclerView.Adapter<EmptyAdapter.H>{boolean selected;public H onCreateViewHolder(android.view.ViewGroup p,int t){View v=new View(p.getContext());v.setLayoutParams(new RecyclerView.LayoutParams(1,1));return new H(v);}public void onBindViewHolder(H h,int p){}public int getItemCount(){return 0;}static final class H extends RecyclerView.ViewHolder{H(View v){super(v);}}}
}