package defpackage;

import android.R;

/* JADX INFO: loaded from: classes.dex */
public abstract class de6 {
    public static final int[] a = {R.attr.selectableItemBackground, org.swiftapps.swiftbackup.R.attr.selectableItemBackground};
    public static final int[] b = {R.attr.summaryOn, R.attr.summaryOff, R.attr.disableDependentsState, org.swiftapps.swiftbackup.R.attr.disableDependentsState, org.swiftapps.swiftbackup.R.attr.summaryOff, org.swiftapps.swiftbackup.R.attr.summaryOn};
    public static final int[] c = {R.attr.dialogTitle, R.attr.dialogMessage, R.attr.dialogIcon, R.attr.positiveButtonText, R.attr.negativeButtonText, R.attr.dialogLayout, org.swiftapps.swiftbackup.R.attr.dialogIcon, org.swiftapps.swiftbackup.R.attr.dialogLayout, org.swiftapps.swiftbackup.R.attr.dialogMessage, org.swiftapps.swiftbackup.R.attr.dialogTitle, org.swiftapps.swiftbackup.R.attr.negativeButtonText, org.swiftapps.swiftbackup.R.attr.positiveButtonText};
    public static final int[] d = {org.swiftapps.swiftbackup.R.attr.useSimpleSummaryProvider};
    public static final int[] e = {R.attr.entries, R.attr.entryValues, org.swiftapps.swiftbackup.R.attr.entries, org.swiftapps.swiftbackup.R.attr.entryValues, org.swiftapps.swiftbackup.R.attr.useSimpleSummaryProvider};
    public static final int[] f = {R.attr.entries, R.attr.entryValues, org.swiftapps.swiftbackup.R.attr.entries, org.swiftapps.swiftbackup.R.attr.entryValues};
    public static final int[] g = {R.attr.icon, R.attr.persistent, R.attr.enabled, R.attr.layout, R.attr.title, R.attr.selectable, R.attr.key, R.attr.summary, R.attr.order, R.attr.widgetLayout, R.attr.dependency, R.attr.defaultValue, R.attr.shouldDisableView, R.attr.fragment, R.attr.singleLineTitle, R.attr.iconSpaceReserved, org.swiftapps.swiftbackup.R.attr.allowDividerAbove, org.swiftapps.swiftbackup.R.attr.allowDividerBelow, org.swiftapps.swiftbackup.R.attr.defaultValue, org.swiftapps.swiftbackup.R.attr.dependency, org.swiftapps.swiftbackup.R.attr.enableCopying, org.swiftapps.swiftbackup.R.attr.enabled, org.swiftapps.swiftbackup.R.attr.fragment, org.swiftapps.swiftbackup.R.attr.icon, org.swiftapps.swiftbackup.R.attr.iconSpaceReserved, org.swiftapps.swiftbackup.R.attr.isPreferenceVisible, org.swiftapps.swiftbackup.R.attr.key, org.swiftapps.swiftbackup.R.attr.layout, org.swiftapps.swiftbackup.R.attr.order, org.swiftapps.swiftbackup.R.attr.persistent, org.swiftapps.swiftbackup.R.attr.selectable, org.swiftapps.swiftbackup.R.attr.shouldDisableView, org.swiftapps.swiftbackup.R.attr.singleLineTitle, org.swiftapps.swiftbackup.R.attr.summary, org.swiftapps.swiftbackup.R.attr.title, org.swiftapps.swiftbackup.R.attr.widgetLayout};
    public static final int[] h = {R.attr.layout, R.attr.divider, R.attr.dividerHeight, org.swiftapps.swiftbackup.R.attr.allowDividerAfterLastItem};
    public static final int[] i = {R.attr.orderingFromXml, org.swiftapps.swiftbackup.R.attr.initialExpandedChildrenCount, org.swiftapps.swiftbackup.R.attr.orderingFromXml};
    public static final int[] j = {R.attr.maxWidth, R.attr.maxHeight, org.swiftapps.swiftbackup.R.attr.maxHeight, org.swiftapps.swiftbackup.R.attr.maxWidth};
    public static final int[] k = {R.attr.layout, R.attr.max, org.swiftapps.swiftbackup.R.attr.adjustable, org.swiftapps.swiftbackup.R.attr.min, org.swiftapps.swiftbackup.R.attr.seekBarIncrement, org.swiftapps.swiftbackup.R.attr.showSeekBarValue, org.swiftapps.swiftbackup.R.attr.updatesContinuously};
    public static final int[] l = {R.attr.summaryOn, R.attr.summaryOff, R.attr.disableDependentsState, R.attr.switchTextOn, R.attr.switchTextOff, org.swiftapps.swiftbackup.R.attr.disableDependentsState, org.swiftapps.swiftbackup.R.attr.summaryOff, org.swiftapps.swiftbackup.R.attr.summaryOn, org.swiftapps.swiftbackup.R.attr.switchTextOff, org.swiftapps.swiftbackup.R.attr.switchTextOn};
    public static final int[] m = {R.attr.summaryOn, R.attr.summaryOff, R.attr.disableDependentsState, R.attr.switchTextOn, R.attr.switchTextOff, org.swiftapps.swiftbackup.R.attr.disableDependentsState, org.swiftapps.swiftbackup.R.attr.summaryOff, org.swiftapps.swiftbackup.R.attr.summaryOn, org.swiftapps.swiftbackup.R.attr.switchTextOff, org.swiftapps.swiftbackup.R.attr.switchTextOn};
}
