package defpackage;

/* JADX INFO: compiled from: r8-map-id-1bff7581625143effd57ac0798e0b9b336d7bf32101928a795c6093adf9a91d0 */
/* JADX INFO: loaded from: classes.dex */
public abstract class le9 {
    public static final yq0 a;
    public static final yq0 b;
    public static final yq0 c;
    public static final yq0 d;
    public static final yq0 e;
    public static final yq0 f;
    public static final yq0 g;
    public static final yq0 h;
    public static final yq0 i;
    public static final yq0 j;
    public static final yq0 k;
    public static final yq0 l;
    public static final yq0 m;
    public static final yq0 n;
    public static final yq0 o;
    public static final yq0 p;
    public static final yq0 q;
    public static final yq0 r;

    static {
        xq0 xq0VarA = yq0.a();
        xq0VarA.a = 3;
        xq0VarA.c = "Google Play In-app Billing API version is less than 3";
        xq0VarA.a();
        xq0 xq0VarA2 = yq0.a();
        xq0VarA2.a = 3;
        xq0VarA2.c = "Google Play In-app Billing API version is less than 9";
        a = xq0VarA2.a();
        xq0 xq0VarA3 = yq0.a();
        xq0VarA3.a = 3;
        xq0VarA3.c = "Billing service unavailable on device.";
        b = xq0VarA3.a();
        xq0 xq0VarA4 = yq0.a();
        xq0VarA4.a = 2;
        xq0VarA4.c = "Billing service unavailable on device.";
        c = xq0VarA4.a();
        xq0 xq0VarA5 = yq0.a();
        xq0VarA5.a = 5;
        xq0VarA5.c = "Client is already in the process of connecting to billing service.";
        d = xq0VarA5.a();
        xq0 xq0VarA6 = yq0.a();
        xq0VarA6.a = 5;
        xq0VarA6.c = "The list of SKUs can't be empty.";
        xq0VarA6.a();
        xq0 xq0VarA7 = yq0.a();
        xq0VarA7.a = 5;
        xq0VarA7.c = "SKU type can't be empty.";
        xq0VarA7.a();
        xq0 xq0VarA8 = yq0.a();
        xq0VarA8.a = 5;
        xq0VarA8.c = "Product type can't be empty.";
        e = xq0VarA8.a();
        xq0 xq0VarA9 = yq0.a();
        xq0VarA9.a = -2;
        xq0VarA9.c = "Client does not support extra params.";
        f = xq0VarA9.a();
        xq0 xq0VarA10 = yq0.a();
        xq0VarA10.a = 5;
        xq0VarA10.c = "Invalid purchase token.";
        g = xq0VarA10.a();
        xq0 xq0VarA11 = yq0.a();
        xq0VarA11.a = 6;
        xq0VarA11.c = "An internal error occurred.";
        h = xq0VarA11.a();
        xq0 xq0VarA12 = yq0.a();
        xq0VarA12.a = 5;
        xq0VarA12.c = "SKU can't be null.";
        xq0VarA12.a();
        xq0 xq0VarA13 = yq0.a();
        xq0VarA13.a = 0;
        i = xq0VarA13.a();
        xq0 xq0VarA14 = yq0.a();
        xq0VarA14.a = -1;
        xq0VarA14.c = "Service connection is disconnected.";
        j = xq0VarA14.a();
        xq0 xq0VarA15 = yq0.a();
        xq0VarA15.a = 2;
        xq0VarA15.c = "Timeout communicating with service.";
        k = xq0VarA15.a();
        xq0 xq0VarA16 = yq0.a();
        xq0VarA16.a = -2;
        xq0VarA16.c = "Client does not support subscriptions.";
        l = xq0VarA16.a();
        xq0 xq0VarA17 = yq0.a();
        xq0VarA17.a = -2;
        xq0VarA17.c = "Client does not support subscriptions update.";
        xq0VarA17.a();
        xq0 xq0VarA18 = yq0.a();
        xq0VarA18.a = -2;
        xq0VarA18.c = "Client does not support get purchase history.";
        xq0VarA18.a();
        xq0 xq0VarA19 = yq0.a();
        xq0VarA19.a = -2;
        xq0VarA19.c = "Client does not support price change confirmation.";
        xq0VarA19.a();
        xq0 xq0VarA20 = yq0.a();
        xq0VarA20.a = -2;
        xq0VarA20.c = "Play Store version installed does not support cross selling products.";
        xq0VarA20.a();
        xq0 xq0VarA21 = yq0.a();
        xq0VarA21.a = -2;
        xq0VarA21.c = "Client does not support multi-item purchases.";
        m = xq0VarA21.a();
        xq0 xq0VarA22 = yq0.a();
        xq0VarA22.a = -2;
        xq0VarA22.c = "Client does not support offer_id_token.";
        n = xq0VarA22.a();
        xq0 xq0VarA23 = yq0.a();
        xq0VarA23.a = -2;
        xq0VarA23.c = "Client does not support ProductDetails.";
        o = xq0VarA23.a();
        xq0 xq0VarA24 = yq0.a();
        xq0VarA24.a = -2;
        xq0VarA24.c = "Client does not support in-app messages.";
        xq0VarA24.a();
        xq0 xq0VarA25 = yq0.a();
        xq0VarA25.a = -2;
        xq0VarA25.c = "Client does not support user choice billing.";
        xq0VarA25.a();
        xq0 xq0VarA26 = yq0.a();
        xq0VarA26.a = -2;
        xq0VarA26.c = "Play Store version installed does not support external offer.";
        xq0VarA26.a();
        xq0 xq0VarA27 = yq0.a();
        xq0VarA27.a = -2;
        xq0VarA27.c = "Play Store version installed does not support multi-item purchases with season pass in one cart.";
        xq0VarA27.a();
        xq0 xq0VarA28 = yq0.a();
        xq0VarA28.a = -2;
        xq0VarA28.c = "Play Store version installed does not support querying AutoPay plan purchase.";
        xq0VarA28.a();
        xq0 xq0VarA29 = yq0.a();
        xq0VarA29.a = -2;
        xq0VarA29.c = "Play Store version installed does not support including suspended subscriptions.";
        xq0VarA29.a();
        xq0 xq0VarA30 = yq0.a();
        xq0VarA30.a = 5;
        xq0VarA30.c = "Unknown feature";
        xq0VarA30.a();
        xq0 xq0VarA31 = yq0.a();
        xq0VarA31.a = -2;
        xq0VarA31.c = "Play Store version installed does not support get billing config.";
        xq0VarA31.a();
        xq0 xq0VarA32 = yq0.a();
        xq0VarA32.a = -2;
        xq0VarA32.c = "Query product details with serialized docid is not supported.";
        xq0VarA32.a();
        xq0 xq0VarA33 = yq0.a();
        xq0VarA33.a = -2;
        xq0VarA33.c = "Play Store version installed does not support launching external offer flow.";
        xq0VarA33.a();
        xq0 xq0VarA34 = yq0.a();
        xq0VarA34.a = 4;
        xq0VarA34.c = "Item is unavailable for purchase.";
        p = xq0VarA34.a();
        xq0 xq0VarA35 = yq0.a();
        xq0VarA35.a = -2;
        xq0VarA35.c = "Query product details with developer specified account is not supported.";
        xq0VarA35.a();
        xq0 xq0VarA36 = yq0.a();
        xq0VarA36.a = -2;
        xq0VarA36.c = "Play Store version installed does not support alternative billing only.";
        xq0VarA36.a();
        xq0 xq0VarA37 = yq0.a();
        xq0VarA37.a = 5;
        xq0VarA37.c = "To use this API you must specify a PurchasesUpdateListener when initializing a BillingClient.";
        q = xq0VarA37.a();
        xq0 xq0VarA38 = yq0.a();
        xq0VarA38.a = 6;
        xq0VarA38.c = "An error occurred while retrieving billing override.";
        r = xq0VarA38.a();
        xq0 xq0VarA39 = yq0.a();
        xq0VarA39.a = -2;
        xq0VarA39.c = "Play Store version installed does not support the provided billing program.";
        xq0VarA39.a();
        xq0 xq0VarA40 = yq0.a();
        xq0VarA40.a = -2;
        xq0VarA40.c = "Play Store version installed does not support launching external links.";
        xq0VarA40.a();
        xq0 xq0VarA41 = yq0.a();
        xq0VarA41.a = 5;
        xq0VarA41.c = "A DeveloperProvidedBillingListener must be provided when initializing the BillingClient in order to use multiple payment options for this billing program.";
        xq0VarA41.a();
    }

    public static yq0 a(int i2, String str) {
        xq0 xq0VarA = yq0.a();
        xq0VarA.a = i2;
        xq0VarA.c = str;
        return xq0VarA.a();
    }
}
