package defpackage;

import java.security.PrivilegedAction;

/* JADX INFO: loaded from: classes.dex */
public final class ou0 implements PrivilegedAction {
    public final /* synthetic */ qu0 a;

    public ou0(qu0 qu0Var) {
        this.a = qu0Var;
    }

    @Override // java.security.PrivilegedAction
    public final Object run() {
        String str;
        String str2;
        qu0.e("org.bouncycastle.jcajce.provider.digest.", qu0.q);
        qu0.e("org.bouncycastle.jcajce.provider.symmetric.", qu0.e);
        qu0.e("org.bouncycastle.jcajce.provider.symmetric.", qu0.f);
        a42[] a42VarArr = qu0.k;
        int i = 0;
        for (int i2 = 0; i2 != a42VarArr.length; i2++) {
            a42 a42Var = a42VarArr[i2];
            e42.a();
            qu0.f("org.bouncycastle.jcajce.provider.symmetric.", a42Var.a());
        }
        qu0.e("org.bouncycastle.jcajce.provider.asymmetric.", qu0.n);
        qu0.e("org.bouncycastle.jcajce.provider.asymmetric.", qu0.p);
        qu0.e("org.bouncycastle.jcajce.provider.keystore.", qu0.r);
        qu0.e("org.bouncycastle.jcajce.provider.drbg.", qu0.t);
        dj7.z(vg0.d);
        dj7.z(vg0.e);
        dj7.z(vg0.f);
        dj7.z(vg0.g);
        dj7.z(vg0.h);
        dj7.z(vg0.i);
        dj7.z(vg0.j);
        dj7.z(vg0.k);
        dj7.z(vg0.l);
        dj7.z(vg0.m);
        dj7.z(vg0.n);
        dj7.z(vg0.o);
        dj7.z(vg0.p);
        dj7.z(vg0.q);
        dj7.z(vg0.r);
        dj7.z(vg0.s);
        dj7.z(vg0.t);
        dj7.z(vg0.u);
        dj7.z(vg0.v);
        dj7.z(vg0.w);
        dj7.z(vg0.x);
        dj7.z(vg0.y);
        dj7.z(vg0.z);
        dj7.z(vg0.A);
        dj7.z(vg0.B);
        dj7.z(vg0.C);
        dj7.z(vg0.D);
        dj7.z(vg0.E);
        dj7.z(vg0.F);
        dj7.z(vg0.G);
        dj7.z(vg0.H);
        dj7.z(vg0.I);
        dj7.z(vg0.J);
        dj7.z(vg0.K);
        dj7.z(vg0.L);
        dj7.z(vg0.M);
        dj7.z(vg0.N);
        dj7.z(vg0.Q);
        dj7.z(vg0.S);
        qu0.d(vg0.U, new yv6());
        dj7.z(new f1("1.3.9999.6.4.10"));
        dj7.z(vg0.V);
        dj7.z(vg0.X);
        dj7.z(vg0.Z);
        qu0.d(bw5.a, new ry0(2));
        int i3 = 1;
        qu0.d(bw5.b, new np4(i3));
        qu0.d(bw5.c, new di0(i3));
        qu0.d(pg4.a, new di0(i3));
        qu0.d(bw5.d, new ix8());
        qu0.d(pg4.b, new ix8());
        qu0.d(tv5.a, new np4(i));
        qu0.d(vg0.c0, new f06());
        qu0.d(pj5.L, new m45());
        qu0.d(pj5.M, new m45());
        qu0.d(pj5.N, new m45());
        f1 f1Var = vg0.p0;
        qu0.d(f1Var, new j33(f1Var));
        f1 f1Var2 = vg0.q0;
        qu0.d(f1Var2, new j33(f1Var2));
        f1 f1Var3 = vg0.r0;
        qu0.d(f1Var3, new j33(f1Var3));
        f1 f1Var4 = vg0.s0;
        qu0.d(f1Var4, new j33(f1Var4));
        qu0.d(vg0.t0, new nl2());
        qu0.d(vg0.u0, new nl2());
        qu0.d(vg0.v0, new nl2());
        qu0.d(vg0.w0, new nl2());
        qu0.d(vg0.x0, new nl2());
        qu0.d(vg0.y0, new nl2());
        qu0.d(vg0.I0, new ry0(i));
        qu0.d(vg0.K0, new ry0(i));
        qu0.d(vg0.M0, new ry0(i));
        qu0.d(vg0.O0, new ry0(i));
        qu0.d(vg0.Q0, new ry0(i));
        qu0.d(vg0.R1, new di0(i));
        qu0.d(vg0.S1, new di0(i));
        qu0.d(vg0.T1, new di0(i));
        qu0.d(vg0.V1, new i24());
        qu0.d(vg0.W1, new i24());
        qu0.d(vg0.X1, new i24());
        qu0.d(vg0.z1, new fp4());
        qu0.d(vg0.A1, new fp4());
        qu0.d(vg0.B1, new fp4());
        qu0.d(vg0.t1, new ry0(i3));
        qu0.d(vg0.u1, new ry0(i3));
        qu0.d(vg0.v1, new ry0(i3));
        qu0.d(vg0.w1, new ry0(i3));
        qu0.d(vg0.Z1, new l95());
        qu0.d(vg0.a2, new l95());
        qu0.d(vg0.b2, new l95());
        qu0.d(vg0.c2, new l95());
        dj7.w(vg0.e2);
        dj7.w(vg0.f2);
        dj7.w(vg0.g2);
        dj7.w(vg0.h2);
        dj7.w(vg0.i2);
        dj7.w(vg0.j2);
        dj7.w(vg0.k2);
        dj7.w(vg0.l2);
        dj7.w(vg0.m2);
        dj7.w(vg0.n2);
        dj7.w(vg0.o2);
        dj7.w(vg0.p2);
        dj7.w(vg0.u2);
        dj7.w(vg0.v2);
        dj7.w(vg0.w2);
        dj7.w(vg0.x2);
        dj7.w(vg0.y2);
        dj7.w(vg0.z2);
        dj7.w(vg0.A2);
        dj7.w(vg0.B2);
        dj7.w(vg0.C2);
        dj7.w(vg0.D2);
        dj7.w(vg0.E2);
        dj7.w(vg0.F2);
        dj7.w(vg0.G2);
        dj7.w(vg0.H2);
        dj7.w(vg0.I2);
        dj7.w(vg0.J2);
        dj7.w(vg0.K2);
        dj7.w(vg0.L2);
        dj7.w(vg0.M2);
        dj7.w(vg0.N2);
        dj7.w(vg0.O2);
        dj7.w(vg0.P2);
        dj7.w(vg0.Q2);
        dj7.w(vg0.R2);
        dj7.w(vg0.S2);
        dj7.w(vg0.T2);
        dj7.w(vg0.U2);
        qu0.d(vg0.V2, new si7());
        qu0 qu0Var = this.a;
        qu0Var.put("X509Store.CERTIFICATE/COLLECTION", "org.bouncycastle.jce.provider.X509StoreCertCollection");
        qu0Var.put("X509Store.ATTRIBUTECERTIFICATE/COLLECTION", "org.bouncycastle.jce.provider.X509StoreAttrCertCollection");
        qu0Var.put("X509Store.CRL/COLLECTION", "org.bouncycastle.jce.provider.X509StoreCRLCollection");
        qu0Var.put("X509Store.CERTIFICATEPAIR/COLLECTION", "org.bouncycastle.jce.provider.X509StoreCertPairCollection");
        qu0Var.put("X509Store.CERTIFICATE/LDAP", "org.bouncycastle.jce.provider.X509StoreLDAPCerts");
        qu0Var.put("X509Store.CRL/LDAP", "org.bouncycastle.jce.provider.X509StoreLDAPCRLs");
        qu0Var.put("X509Store.ATTRIBUTECERTIFICATE/LDAP", "org.bouncycastle.jce.provider.X509StoreLDAPAttrCerts");
        qu0Var.put("X509Store.CERTIFICATEPAIR/LDAP", "org.bouncycastle.jce.provider.X509StoreLDAPCertPairs");
        qu0Var.put("X509StreamParser.CERTIFICATE", "org.bouncycastle.jce.provider.X509CertParser");
        qu0Var.put("X509StreamParser.ATTRIBUTECERTIFICATE", "org.bouncycastle.jce.provider.X509AttrCertParser");
        qu0Var.put("X509StreamParser.CRL", "org.bouncycastle.jce.provider.X509CRLParser");
        qu0Var.put("X509StreamParser.CERTIFICATEPAIR", "org.bouncycastle.jce.provider.X509CertPairParser");
        qu0Var.put("Cipher.BROKENPBEWITHMD5ANDDES", "org.bouncycastle.jce.provider.BrokenJCEBlockCipher$BrokePBEWithMD5AndDES");
        qu0Var.put("Cipher.BROKENPBEWITHSHA1ANDDES", "org.bouncycastle.jce.provider.BrokenJCEBlockCipher$BrokePBEWithSHA1AndDES");
        qu0Var.put("Cipher.OLDPBEWITHSHAANDTWOFISH-CBC", "org.bouncycastle.jce.provider.BrokenJCEBlockCipher$OldPBEWithSHAAndTwofish");
        Class cls = qu0.d;
        qu0Var.put("CertPathValidator.RFC3281", "org.bouncycastle.jce.provider.PKIXAttrCertPathValidatorSpi");
        qu0Var.put("CertPathBuilder.RFC3281", "org.bouncycastle.jce.provider.PKIXAttrCertPathBuilderSpi");
        if (cls != null) {
            str = "org.bouncycastle.jce.provider.PKIXCertPathValidatorSpi_8";
            qu0Var.put("CertPathValidator.RFC3280", "org.bouncycastle.jce.provider.PKIXCertPathValidatorSpi_8");
            str2 = "org.bouncycastle.jce.provider.PKIXCertPathBuilderSpi_8";
        } else {
            str = "org.bouncycastle.jce.provider.PKIXCertPathValidatorSpi";
            qu0Var.put("CertPathValidator.RFC3280", "org.bouncycastle.jce.provider.PKIXCertPathValidatorSpi");
            str2 = "org.bouncycastle.jce.provider.PKIXCertPathBuilderSpi";
        }
        qu0Var.put("CertPathBuilder.RFC3280", str2);
        qu0Var.put("CertPathValidator.PKIX", str);
        qu0Var.put("CertPathBuilder.PKIX", str2);
        qu0Var.put("CertStore.Collection", "org.bouncycastle.jce.provider.CertStoreCollectionSpi");
        qu0Var.put("CertStore.LDAP", "org.bouncycastle.jce.provider.X509LDAPCertStoreSpi");
        qu0Var.put("CertStore.Multi", "org.bouncycastle.jce.provider.MultiCertStoreSpi");
        qu0Var.put("Alg.Alias.CertStore.X509LDAP", "LDAP");
        return null;
    }
}
