package com.bare.detail;
import android.app.Activity; import android.content.Intent; import android.os.Bundle; import android.os.Parcelable; import android.widget.TextView; import androidx.annotation.Nullable; import androidx.appcompat.app.AppCompatActivity; import androidx.appcompat.widget.Toolbar; import com.bare.R; import com.google.android.material.dialog.MaterialAlertDialogBuilder;
public final class DetailActivity extends AppCompatActivity {
 private static final String APP_PARCEL="APP_PARCEL"; private static final String SHORTCUT="detail_launched_from_shortcut"; private Parcelable appParcel;
 private final java.util.LinkedHashSet<RestorePart> selectedParts=new java.util.LinkedHashSet<>();
 @Override protected void onCreate(@Nullable Bundle state){ super.onCreate(state); setContentView(R.layout.detail_activity); Toolbar t=findViewById(R.id.toolbar); setSupportActionBar(t); if(getSupportActionBar()!=null){getSupportActionBar().setDisplayHomeAsUpEnabled(true);getSupportActionBar().setTitle(R.string.app_detail);} appParcel=state!=null?state.getParcelable(APP_PARCEL):getIntent().getParcelableExtra(APP_PARCEL); if(appParcel==null&&!getIntent().getBooleanExtra(SHORTCUT,false)){finish();return;} if(appParcel!=null){((TextView)findViewById(R.id.tv_info)).setText(R.string.app_info_contract_ready);} findViewById(R.id.btn_backup).setOnClickListener(v->boundary(R.string.backup)); findViewById(R.id.btn_restore).setOnClickListener(v->restoreBoundary()); }
 private void boundary(int title){new MaterialAlertDialogBuilder(this).setTitle(title).setMessage(R.string.apps_engine_boundary).setPositiveButton(R.string.close,null).show();}
 private void restoreBoundary(){ final RestorePart[] values=RestorePart.values(); boolean[] checked=new boolean[values.length]; for(int i=0;i<values.length;i++)checked[i]=selectedParts.contains(values[i]); new MaterialAlertDialogBuilder(this).setTitle(R.string.restore).setMultiChoiceItems(new String[]{"APK","DATA","EXTERNAL_DATA","MEDIA","EXPANSION"},checked,(d,w,isChecked)->{if(isChecked)selectedParts.add(values[w]);else selectedParts.remove(values[w]);}).setPositiveButton(android.R.string.ok,(d,w)->{if(selectedParts.isEmpty())selectedParts.add(RestorePart.APK);boundary(R.string.restore);}).setNegativeButton(R.string.cancel,null).show(); }
 @Override protected void onSaveInstanceState(Bundle out){if(appParcel!=null)out.putParcelable(APP_PARCEL,appParcel);out.putStringArrayList("restore_parts",new java.util.ArrayList<>(java.util.Arrays.asList(selectedParts.stream().map(Enum::name).toArray(String[]::new))));super.onSaveInstanceState(out);}
 public enum RestorePart { APK, DATA, EXTERNAL_DATA, MEDIA, EXPANSION }
 @Override public boolean onSupportNavigateUp(){setResult(Activity.RESULT_CANCELED);finish();return true;}
 @Override protected void onNewIntent(Intent intent){super.onNewIntent(intent);setIntent(intent); if(intent.getBooleanExtra(SHORTCUT,false)){appParcel=intent.getParcelableExtra(APP_PARCEL);}}
}