package com.bare.messagescalls.dash;
import android.Manifest; import android.app.Activity; import android.content.Intent; import android.content.pm.PackageManager; import android.os.Bundle; import android.view.Menu; import android.view.MenuItem; import android.widget.TextView; import androidx.annotation.Nullable; import androidx.appcompat.app.AppCompatActivity; import androidx.appcompat.widget.Toolbar; import com.bare.R; import com.bare.messagescalls.backups.MessagesBackupsActivity; import com.bare.messagescalls.conversationsview.ConversationsActivity; import com.bare.settings.SettingsActivity; import com.bare.settings.SettingsDetailActivity; import com.google.android.material.dialog.MaterialAlertDialogBuilder;
public final class MessagesDashActivity extends AppCompatActivity {
 private static final int PERMISSION_REQUEST=9785;
 @Override protected void onCreate(@Nullable Bundle s){super.onCreate(s);setContentView(R.layout.smscalls_dash_activity);Toolbar t=findViewById(R.id.toolbar);t.setTitle(R.string.messages);setSupportActionBar(t);if(getSupportActionBar()!=null)getSupportActionBar().setDisplayHomeAsUpEnabled(true);findViewById(R.id.btn_create_backup).setOnClickListener(v->boundary(R.string.messages_backup));findViewById(R.id.tv_local_state).setOnClickListener(v->startActivity(new Intent(this,MessagesBackupsActivity.class)));requestMessagePermissions();}
 private void requestMessagePermissions(){if(checkSelfPermission(Manifest.permission.READ_SMS)==PackageManager.PERMISSION_GRANTED&&checkSelfPermission(Manifest.permission.READ_CONTACTS)==PackageManager.PERMISSION_GRANTED)return;requestPermissions(new String[]{Manifest.permission.READ_SMS,Manifest.permission.READ_CONTACTS},PERMISSION_REQUEST);}
 @Override public void onRequestPermissionsResult(int r,String[] p,int[] a){super.onRequestPermissionsResult(r,p,a);if(r!=PERMISSION_REQUEST)return;for(int x:a)if(x!=PackageManager.PERMISSION_GRANTED){((TextView)findViewById(R.id.tv_local_state)).setText(R.string.messages_permission_required);break;}}
 private void boundary(int title){new MaterialAlertDialogBuilder(this).setTitle(title).setMessage(R.string.p3_activity_boundary).setPositiveButton(R.string.close,null).show();}
 @Override public boolean onCreateOptionsMenu(Menu m){getMenuInflater().inflate(R.menu.menu_sms_dash,m);m.findItem(R.id.action_view_messages).setVisible(false);return true;}
 @Override public boolean onOptionsItemSelected(MenuItem i){if(i.getItemId()==R.id.action_sms_settings){Intent x=new Intent(this,SettingsDetailActivity.class);x.putExtra("category",2);x.putExtra("category_title",getString(R.string.messages_backups));startActivity(x);return true;}if(i.getItemId()==R.id.action_view_messages){startActivity(new Intent(this,ConversationsActivity.class));return true;}if(i.getItemId()==R.id.action_settings){startActivity(new Intent(this,SettingsActivity.class));return true;}return super.onOptionsItemSelected(i);}
 @Override public boolean onSupportNavigateUp(){setResult(Activity.RESULT_CANCELED);finish();return true;}
}